version: "3"
services:
    site:
        restart: always
        stdin_open: true
        ports:
            - "3000:3000"
        build:
            dockerfile: Dockerfile
            context: ./app
    api:
        restart: always
        stdin_open: true
        ports:
            - "4000:4000"
        build:
            dockerfile: Dockerfile
            context: ./api
